<?php
session_start();
require_once __DIR__ . "/../config/database.php";
if (!isset($_SESSION["user_id"])) { header("Location: ../auth/login.php"); exit(); }
$id = (int)($_GET["id"] ?? 0);
$stmt = $conn->prepare("SELECT * FROM tasks WHERE id = ?");
$stmt->bind_param("i", $id); $stmt->execute(); $task = $stmt->get_result()->fetch_assoc(); $stmt->close();
if (!$task) { header("Location: index.php"); exit(); }
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>View Task</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><div class="container mt-5"><div class="row justify-content-center"><div class="col-md-7"><div class="card shadow"><div class="card-header bg-primary text-white d-flex justify-content-between"><h4 class="mb-0">Task Details</h4><span><?= $task["is_completed"] ? "Completed" : "Incomplete" ?></span></div><div class="card-body"><?php if (isset($_GET["message"])): ?><div class="alert alert-success"><?= htmlspecialchars($_GET["message"]) ?></div><?php endif; ?><dl class="row"><dt class="col-sm-4">ID</dt><dd class="col-sm-8"><?= (int)$task["id"] ?></dd><dt class="col-sm-4">Task</dt><dd class="col-sm-8"><?= htmlspecialchars($task["Task"]) ?></dd><dt class="col-sm-4">Description</dt><dd class="col-sm-8"><?= nl2br(htmlspecialchars($task["Description"] ?: "No description provided.")) ?></dd><dt class="col-sm-4">Priority</dt><dd class="col-sm-8"><?= htmlspecialchars($task["priority"]) ?></dd><dt class="col-sm-4">Progress</dt><dd class="col-sm-8"><?= htmlspecialchars($task["progress"]) ?></dd><dt class="col-sm-4">Availability</dt><dd class="col-sm-8"><?= (int)$task["status"] ? "Active" : "Inactive" ?></dd><dt class="col-sm-4">Completion</dt><dd class="col-sm-8"><?= $task["is_completed"] ? "Completed" : "Incomplete" ?></dd></dl><a class="btn btn-success" href="toggle_complete.php?id=<?= $id ?>&return=<?= urlencode($_SERVER["REQUEST_URI"]) ?>"><?= $task["is_completed"] ? "Mark incomplete" : "Mark complete" ?></a> <a class="btn btn-secondary" href="index.php">Back</a></div></div></div></div></div></body></html>
